### ISSUE TITLE
Implement Dialogue System

### ISSUE THREAD

**Issue by Bandit304** [Bandit304/MathDimension#9]
### TODO
- [x] Add dialogue UI
- [x] Add Interactable that displays dialogue on interact
- [x] Allow multiple lines of dialogue to be displayed during the same interaction
- [x] Allow one Interactable to cycle through multiple "scripts" of dialogue
- [ ] Add branching dialogue options
  - [ ] Add dialogue options the player can choose
  - [ ] Display different dialogue depending on option chosen
  - [ ] Include an "OnChoose" method/event to run certain code depending on which choice was made
